# Generated by Django 5.1.4 on 2024-12-13 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contentitem_faq_venueinformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Theme name (e.g., 'SOI Default', 'Dark Mode', 'High Contrast')", max_length=100, unique=True)),
                ('theme_type', models.CharField(choices=[('ADMIN', 'Admin Interface'), ('PUBLIC', 'Public Website'), ('MOBILE', 'Mobile Interface'), ('EMAIL', 'Email Templates')], default='ADMIN', help_text='Type of interface this theme applies to', max_length=20)),
                ('primary_color', models.CharField(default='#2E7D32', help_text='Primary brand color (hex format: #RRGGBB)', max_length=7)),
                ('secondary_color', models.CharField(default='#1B5E20', help_text='Secondary brand color (hex format: #RRGGBB)', max_length=7)),
                ('accent_color', models.CharField(default='#FFD700', help_text='Accent color for highlights (hex format: #RRGGBB)', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Main background color (hex format: #RRGGBB)', max_length=7)),
                ('surface_color', models.CharField(default='#F8F9FA', help_text='Surface/card background color (hex format: #RRGGBB)', max_length=7)),
                ('text_primary', models.CharField(default='#212529', help_text='Primary text color (hex format: #RRGGBB)', max_length=7)),
                ('text_secondary', models.CharField(default='#6C757D', help_text='Secondary text color (hex format: #RRGGBB)', max_length=7)),
                ('text_on_primary', models.CharField(default='#FFFFFF', help_text='Text color on primary background (hex format: #RRGGBB)', max_length=7)),
                ('success_color', models.CharField(default='#28A745', help_text='Success/positive action color (hex format: #RRGGBB)', max_length=7)),
                ('warning_color', models.CharField(default='#FFC107', help_text='Warning/caution color (hex format: #RRGGBB)', max_length=7)),
                ('error_color', models.CharField(default='#DC3545', help_text='Error/danger color (hex format: #RRGGBB)', max_length=7)),
                ('info_color', models.CharField(default='#17A2B8', help_text='Information color (hex format: #RRGGBB)', max_length=7)),
                ('font_family_primary', models.CharField(default="'Segoe UI', Tahoma, Geneva, Verdana, sans-serif", help_text='Primary font family CSS declaration', max_length=200)),
                ('font_family_secondary', models.CharField(default="'Courier New', monospace", help_text='Secondary font family for code/monospace text', max_length=200)),
                ('font_size_base', models.CharField(default='14px', help_text="Base font size (e.g., '14px', '1rem')", max_length=10)),
                ('border_radius', models.CharField(default='6px', help_text='Default border radius for rounded corners', max_length=10)),
                ('box_shadow', models.CharField(default='0 2px 8px rgba(0,0,0,0.1)', help_text='Default box shadow CSS', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL to logo image (optional)')),
                ('favicon_url', models.URLField(blank=True, help_text='URL to favicon (optional)')),
                ('custom_css', models.TextField(blank=True, help_text='Additional custom CSS rules (advanced users only)')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this theme is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default theme for new users')),
                ('is_dark_mode', models.BooleanField(default=False, help_text='Whether this is a dark mode theme')),
                ('accessibility_compliant', models.BooleanField(default=True, help_text='Whether this theme meets accessibility standards')),
                ('description', models.TextField(blank=True, help_text='Description of this theme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['theme_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_dark_mode', models.BooleanField(default=False, help_text='Prefer dark mode themes when available')),
                ('use_high_contrast', models.BooleanField(default=False, help_text='Use high contrast themes for accessibility')),
                ('font_size_preference', models.CharField(choices=[('SMALL', 'Small (12px)'), ('NORMAL', 'Normal (14px)'), ('LARGE', 'Large (16px)'), ('EXTRA_LARGE', 'Extra Large (18px)')], default='NORMAL', help_text='Preferred font size', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_theme', models.ForeignKey(blank=True, help_text='Preferred admin interface theme', limit_choices_to={'theme_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='common.theme')),
                ('mobile_theme', models.ForeignKey(blank=True, help_text='Preferred mobile interface theme', limit_choices_to={'theme_type': 'MOBILE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_users', to='common.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Theme Preference',
                'verbose_name_plural': 'User Theme Preferences',
            },
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('theme_type', 'is_active'), name='unique_active_theme_per_type'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('theme_type', 'is_default'), name='unique_default_theme_per_type'),
        ),
    ]
